Trainer.create!(first_name: 'Austin', last_name: 'Meier', username: 'admin', admin: 'true', email: 'admin@admin.com', password: 'password', password_confirmation: 'password')
Athlete.create!(first_name: 'Athlete', last_name: '1', sport: 'Football')
Athlete.create!(first_name: 'Athlete', last_name: '2', sport: 'Baseball')
Athlete.create!(first_name: 'Athlete', last_name: '3', sport: 'Cross-Country')
Injury.create!(injury_location: 'Knee', status: 'Full')
Injury.create!(injury_location: 'Back', status: 'None')
